# Generated by Django 5.1.6 on 2025-03-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_shortened_db_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortened_db',
            name='origin_url_en',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shortened_db',
            name='origin_url_ru',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shortened_db',
            name='origin_url_uz',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shortened_db',
            name='shorten_url_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shortened_db',
            name='shorten_url_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shortened_db',
            name='shorten_url_uz',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
