# Generated by Django 5.1.1 on 2025-03-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_shortenedurl_delete_shortened_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'ordering': ['-created_at']},
        ),
    ]
