# Generated by Django 5.1.1 on 2025-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_shortenedurl_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='last_accessed',
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
